# A workflow for testing the workshop setup in different operating systems

name: Test Workshop Setup OS 

# Controls when the action will run. Workflow runs when manually triggered using the UI
on:
  workflow_dispatch:
    
jobs:
  workshop_setup:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        # list of Os's
        R: ['4.3.3']
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{matrix.R}}
      - run: Rscript -e 'print("hello")'
