# A workflow for testing the workshop setup in different operating systems

name: Test Workshop Setup OS 

# Controls when the action will run. Workflow runs when manually triggered using the UI
on:
  workflow_dispatch:
    
jobs:
  workshop_setup:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        # list of Os's
        R: ['4.3.3']
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{matrix.R}}
          rtools-version: '4.3.x' 
      - run: Rscript -e 'print("hello")'
      - name: Install GDAL, GEOS, and PROJ.4
        if: matrix.os == 'macos-latest'
        run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        shell: bash
        
